---


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - python


- name: "Instalando os pacotes do Python 3"
  apt:
    name: "{{ python_packages }}"
    state: present
  become: true
  tags:
    - python