---

- name: Incluindo tarefas especificas para o SO
  include_tasks: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution | lower }}.yml"
   - "{{ ansible_os_family | lower }}.yml"
   - "os_defaults.yml"
  tags: 
   - main
   - python


- name: "Instalando o Virtualenv"
  when: os_default is not defined
  pip:
    name: virtualenv
    state: latest
    executable: pip3
  become: true
  tags:
    - python